# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  # contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "欢迎来到我的主页"
  [zh.params]
    description = "Site description in Chinese..."
  [[zh.menu.main]]
    name = "关于"
    url = "#about"
    weight = 1
    
  [[zh.menu.main]]
    name = "教育"
    url = "#education"
    weight = 21
    
  [[zh.menu.main]]
    name = "技能"
    url = "#skills"
    weight = 31
    
  [[zh.menu.main]]
    name = "项目"
    url = "#projects"
    weight = 40
    
  [[zh.menu.main]]
    name = "获奖"
    url = "#skills"
    weight = 50
    
  [[zh.menu.main]]
    name = "发表"
    url = "#skills"
    weight = 60
    
  [[zh.menu.main]]
    name = "联系"
    url = "#skills"
    weight = 70
    
  [[zh.menu.main]]
    name = "English"
    url = "/en/"
    weight = 80
    
  [[zh.menu.main]]
    name = "日本語"
    url = "/ja/"
    weight = 90    


[ja]
  languageCode = "ja"
  contentDir = "content/ja"
  title = "私のウェブサイトへようこそ"
  [ja.params]
    description = "Site description in Japanese..."
  [[ja.menu.main]]
    name = "基本情報"
    url = "#about"
    weight = 1
    
  [[ja.menu.main]]
    name = "教育"
    url = "#education"
    weight = 21
    
  [[ja.menu.main]]
    name = "スキル"
    url = "#skills"
    weight = 31
    
  [[ja.menu.main]]
    name = "プロジェクト"
    url = "#projects"
    weight = 40
    
  [[ja.menu.main]]
    name = "受賞"
    url = "#accomplishments"
    weight = 50
    
  [[ja.menu.main]]
    name = "研究業績"
    url = "#publications"
    weight = 60
    
  [[ja.menu.main]]
    name = "連絡"
    url = "#concat"
    weight = 70
    
  [[ja.menu.main]]
    name = "English"
    url = "/en/"
    weight = 80
    
  [[ja.menu.main]]
    name = "中文"
    url = "/zh/"
    weight = 90    
